#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment_System_DBMS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ENROLLMENT_DB")]
	public partial class EnrollmentDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCOLLEGE(COLLEGE instance);
    partial void UpdateCOLLEGE(COLLEGE instance);
    partial void DeleteCOLLEGE(COLLEGE instance);
    partial void InsertSTUDENT(STUDENT instance);
    partial void UpdateSTUDENT(STUDENT instance);
    partial void DeleteSTUDENT(STUDENT instance);
    partial void InsertYEAR_LEVEL(YEAR_LEVEL instance);
    partial void UpdateYEAR_LEVEL(YEAR_LEVEL instance);
    partial void DeleteYEAR_LEVEL(YEAR_LEVEL instance);
    partial void InsertPROGRAM(PROGRAM instance);
    partial void UpdatePROGRAM(PROGRAM instance);
    partial void DeletePROGRAM(PROGRAM instance);
    #endregion
		
		public EnrollmentDBDataContext() : 
				base(global::Enrollment_System_DBMS.Properties.Settings.Default.ENROLLMENT_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<COLLEGE> COLLEGEs
		{
			get
			{
				return this.GetTable<COLLEGE>();
			}
		}
		
		public System.Data.Linq.Table<STUDENT> STUDENTs
		{
			get
			{
				return this.GetTable<STUDENT>();
			}
		}
		
		public System.Data.Linq.Table<YEAR_LEVEL> YEAR_LEVELs
		{
			get
			{
				return this.GetTable<YEAR_LEVEL>();
			}
		}
		
		public System.Data.Linq.Table<ID_STORAGE> ID_STORAGEs
		{
			get
			{
				return this.GetTable<ID_STORAGE>();
			}
		}
		
		public System.Data.Linq.Table<PROGRAM> PROGRAMs
		{
			get
			{
				return this.GetTable<PROGRAM>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_YEAR_LEVEL")]
		public ISingleResult<SP_YEAR_LEVELResult> SP_YEAR_LEVEL()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_YEAR_LEVELResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PROGRAM_ID")]
		public ISingleResult<SP_PROGRAM_IDResult> SP_PROGRAM_ID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROG_NAME", DbType="NVarChar(255)")] string pROG_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pROG_NAME);
			return ((ISingleResult<SP_PROGRAM_IDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PROGRAM")]
		public ISingleResult<SP_PROGRAMResult> SP_PROGRAM()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_PROGRAMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_COLLEGE")]
		public ISingleResult<SP_COLLEGEResult> SP_COLLEGE()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_COLLEGEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERT_STUDENT_INFORMATION")]
		public int SP_INSERT_STUDENT_INFORMATION(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_PHOTO", DbType="VarBinary(MAX)")] System.Data.Linq.Binary sTUD_PHOTO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_FIRSTNAME", DbType="NVarChar(55)")] string sTUD_FIRSTNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_MIDDLENAME", DbType="NVarChar(55)")] string sTUD_MIDDLENAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_LASTNAME", DbType="NVarChar(55)")] string sTUD_LASTNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_AGE", DbType="NVarChar(2)")] string sTUD_AGE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_BIRTH_DATE", DbType="Date")] System.Nullable<System.DateTime> sTUD_BIRTH_DATE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_PLACE_OF_BIRTH", DbType="NVarChar(100)")] string sTUD_PLACE_OF_BIRTH, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_ADDRESS", DbType="NVarChar(100)")] string sTUD_ADDRESS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_EMAIL", DbType="NVarChar(55)")] string sTUD_EMAIL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_MOBILE", DbType="NVarChar(13)")] string sTUD_MOBILE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_GENDER", DbType="NVarChar(55)")] string sTUD_GENDER, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_STATUS", DbType="NVarChar(20)")] string sTUD_STATUS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_CREATED_AT", DbType="Date")] System.Nullable<System.DateTime> sTUD_CREATED_AT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_UPDATED_AT", DbType="Date")] System.Nullable<System.DateTime> sTUD_UPDATED_AT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="COLL_ID", DbType="Int")] System.Nullable<int> cOLL_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROG_ID", DbType="Int")] System.Nullable<int> pROG_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR_ID", DbType="Int")] System.Nullable<int> yEAR_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTUD_PHOTO, sTUD_FIRSTNAME, sTUD_MIDDLENAME, sTUD_LASTNAME, sTUD_AGE, sTUD_BIRTH_DATE, sTUD_PLACE_OF_BIRTH, sTUD_ADDRESS, sTUD_EMAIL, sTUD_MOBILE, sTUD_GENDER, sTUD_STATUS, sTUD_CREATED_AT, sTUD_UPDATED_AT, cOLL_ID, pROG_ID, yEAR_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_COLLEGE_ID")]
		public ISingleResult<SP_COLLEGE_IDResult> SP_COLLEGE_ID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="COLL_NAME", DbType="NVarChar(500)")] string cOLL_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cOLL_NAME);
			return ((ISingleResult<SP_COLLEGE_IDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERT_PROGRAM")]
		public int SP_INSERT_PROGRAM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROG_NAME", DbType="NVarChar(255)")] string pROG_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROG_CREATED_AT", DbType="Date")] System.Nullable<System.DateTime> pROG_CREATED_AT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROG_UPDATED_AT", DbType="Date")] System.Nullable<System.DateTime> pROG_UPDATED_AT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pROG_NAME, pROG_CREATED_AT, pROG_UPDATED_AT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERT_COLLEGE")]
		public int SP_INSERT_COLLEGE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="COLL_NAME", DbType="NVarChar(500)")] string cOLL_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COLL_CREATED_AT", DbType="Date")] System.Nullable<System.DateTime> cOLL_CREATED_AT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COLL_UPDATED_AT", DbType="Date")] System.Nullable<System.DateTime> cOLL_UPDATED_AT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cOLL_NAME, cOLL_CREATED_AT, cOLL_UPDATED_AT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_YEAR_LEVEL_ID")]
		public ISingleResult<SP_YEAR_LEVEL_IDResult> SP_YEAR_LEVEL_ID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR_NAME", DbType="NVarChar(55)")] string yEAR_NAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yEAR_NAME);
			return ((ISingleResult<SP_YEAR_LEVEL_IDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DISPLAY_STUDENT_RECORDS")]
		public ISingleResult<SP_DISPLAY_STUDENT_RECORDSResult> SP_DISPLAY_STUDENT_RECORDS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_DISPLAY_STUDENT_RECORDSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SEARCH_STUDENT_RECORDS_BY_TEXTBOX")]
		public ISingleResult<SP_SEARCH_STUDENT_RECORDS_BY_TEXTBOXResult> SP_SEARCH_STUDENT_RECORDS_BY_TEXTBOX([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KEY", DbType="VarChar(MAX)")] string kEY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kEY);
			return ((ISingleResult<SP_SEARCH_STUDENT_RECORDS_BY_TEXTBOXResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ID_STORAGE")]
		public int SP_ID_STORAGE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="NVarChar(20)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UPDATE_STUDENT_INFORMATION")]
		public int SP_UPDATE_STUDENT_INFORMATION(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="KEY", DbType="NVarChar(MAX)")] string kEY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_PHOTO", DbType="VarBinary(MAX)")] System.Data.Linq.Binary sTUD_PHOTO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_FIRSTNAME", DbType="NVarChar(55)")] string sTUD_FIRSTNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_MIDDLENAME", DbType="NVarChar(55)")] string sTUD_MIDDLENAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_LASTNAME", DbType="NVarChar(55)")] string sTUD_LASTNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_AGE", DbType="NVarChar(2)")] string sTUD_AGE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_BIRTH_DATE", DbType="Date")] System.Nullable<System.DateTime> sTUD_BIRTH_DATE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_PLACE_OF_BIRTH", DbType="NVarChar(100)")] string sTUD_PLACE_OF_BIRTH, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_ADDRESS", DbType="NVarChar(100)")] string sTUD_ADDRESS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_EMAIL", DbType="NVarChar(55)")] string sTUD_EMAIL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_MOBILE", DbType="NVarChar(13)")] string sTUD_MOBILE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_GENDER", DbType="NVarChar(55)")] string sTUD_GENDER, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_UPDATED_AT", DbType="Date")] System.Nullable<System.DateTime> sTUD_UPDATED_AT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="COLL_ID", DbType="Int")] System.Nullable<int> cOLL_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROG_ID", DbType="Int")] System.Nullable<int> pROG_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR_ID", DbType="Int")] System.Nullable<int> yEAR_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kEY, sTUD_PHOTO, sTUD_FIRSTNAME, sTUD_MIDDLENAME, sTUD_LASTNAME, sTUD_AGE, sTUD_BIRTH_DATE, sTUD_PLACE_OF_BIRTH, sTUD_ADDRESS, sTUD_EMAIL, sTUD_MOBILE, sTUD_GENDER, sTUD_UPDATED_AT, cOLL_ID, pROG_ID, yEAR_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DELETE_STUDENT")]
		public int SP_DELETE_STUDENT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KEY", DbType="VarChar(MAX)")] string kEY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kEY);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DISPLAY_STUDENT_INFORMATION")]
		public ISingleResult<SP_DISPLAY_STUDENT_INFORMATIONResult> SP_DISPLAY_STUDENT_INFORMATION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KEY", DbType="VarChar(MAX)")] string kEY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kEY);
			return ((ISingleResult<SP_DISPLAY_STUDENT_INFORMATIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SPECIFIC_PROGRAM_FROM_COLLEGE")]
		public ISingleResult<SP_SPECIFIC_PROGRAM_FROM_COLLEGEResult> SP_SPECIFIC_PROGRAM_FROM_COLLEGE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KEY", DbType="Int")] System.Nullable<int> kEY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kEY);
			return ((ISingleResult<SP_SPECIFIC_PROGRAM_FROM_COLLEGEResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COLLEGE")]
	public partial class COLLEGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _COLL_ID;
		
		private string _COLL_NAME;
		
		private System.Nullable<System.DateTime> _COLL_CREATED_AT;
		
		private System.Nullable<System.DateTime> _COLL_UPDATED_AT;
		
		private EntitySet<STUDENT> _STUDENTs;
		
		private EntitySet<PROGRAM> _PROGRAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOLL_IDChanging(int value);
    partial void OnCOLL_IDChanged();
    partial void OnCOLL_NAMEChanging(string value);
    partial void OnCOLL_NAMEChanged();
    partial void OnCOLL_CREATED_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnCOLL_CREATED_ATChanged();
    partial void OnCOLL_UPDATED_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnCOLL_UPDATED_ATChanged();
    #endregion
		
		public COLLEGE()
		{
			this._STUDENTs = new EntitySet<STUDENT>(new Action<STUDENT>(this.attach_STUDENTs), new Action<STUDENT>(this.detach_STUDENTs));
			this._PROGRAMs = new EntitySet<PROGRAM>(new Action<PROGRAM>(this.attach_PROGRAMs), new Action<PROGRAM>(this.detach_PROGRAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int COLL_ID
		{
			get
			{
				return this._COLL_ID;
			}
			set
			{
				if ((this._COLL_ID != value))
				{
					this.OnCOLL_IDChanging(value);
					this.SendPropertyChanging();
					this._COLL_ID = value;
					this.SendPropertyChanged("COLL_ID");
					this.OnCOLL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_NAME", DbType="NVarChar(255)")]
		public string COLL_NAME
		{
			get
			{
				return this._COLL_NAME;
			}
			set
			{
				if ((this._COLL_NAME != value))
				{
					this.OnCOLL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._COLL_NAME = value;
					this.SendPropertyChanged("COLL_NAME");
					this.OnCOLL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_CREATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> COLL_CREATED_AT
		{
			get
			{
				return this._COLL_CREATED_AT;
			}
			set
			{
				if ((this._COLL_CREATED_AT != value))
				{
					this.OnCOLL_CREATED_ATChanging(value);
					this.SendPropertyChanging();
					this._COLL_CREATED_AT = value;
					this.SendPropertyChanged("COLL_CREATED_AT");
					this.OnCOLL_CREATED_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_UPDATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> COLL_UPDATED_AT
		{
			get
			{
				return this._COLL_UPDATED_AT;
			}
			set
			{
				if ((this._COLL_UPDATED_AT != value))
				{
					this.OnCOLL_UPDATED_ATChanging(value);
					this.SendPropertyChanging();
					this._COLL_UPDATED_AT = value;
					this.SendPropertyChanged("COLL_UPDATED_AT");
					this.OnCOLL_UPDATED_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COLLEGE_STUDENT", Storage="_STUDENTs", ThisKey="COLL_ID", OtherKey="COLL_ID")]
		public EntitySet<STUDENT> STUDENTs
		{
			get
			{
				return this._STUDENTs;
			}
			set
			{
				this._STUDENTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COLLEGE_PROGRAM", Storage="_PROGRAMs", ThisKey="COLL_ID", OtherKey="COLL_ID")]
		public EntitySet<PROGRAM> PROGRAMs
		{
			get
			{
				return this._PROGRAMs;
			}
			set
			{
				this._PROGRAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_STUDENTs(STUDENT entity)
		{
			this.SendPropertyChanging();
			entity.COLLEGE = this;
		}
		
		private void detach_STUDENTs(STUDENT entity)
		{
			this.SendPropertyChanging();
			entity.COLLEGE = null;
		}
		
		private void attach_PROGRAMs(PROGRAM entity)
		{
			this.SendPropertyChanging();
			entity.COLLEGE = this;
		}
		
		private void detach_PROGRAMs(PROGRAM entity)
		{
			this.SendPropertyChanging();
			entity.COLLEGE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STUDENT")]
	public partial class STUDENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STUD_NUMBER;
		
		private string _STUD_ID;
		
		private System.Data.Linq.Binary _STUD_PHOTO;
		
		private string _STUD_FIRSTNAME;
		
		private string _STUD_MIDDLENAME;
		
		private string _STUD_LASTNAME;
		
		private string _STUD_AGE;
		
		private System.DateTime _STUD_BIRTH_DATE;
		
		private string _STUD_PLACE_OF_BIRTH;
		
		private string _STUD_ADDRESS;
		
		private string _STUD_EMAIL;
		
		private string _STUD_MOBILE;
		
		private string _STUD_GENDER;
		
		private string _STUD_STATUS;
		
		private System.DateTime _STUD_CREATED_AT;
		
		private System.Nullable<System.DateTime> _STUD_UPDATED_AT;
		
		private System.Nullable<int> _COLL_ID;
		
		private System.Nullable<int> _PROG_ID;
		
		private System.Nullable<int> _YEAR_ID;
		
		private EntityRef<COLLEGE> _COLLEGE;
		
		private EntityRef<YEAR_LEVEL> _YEAR_LEVEL;
		
		private EntityRef<PROGRAM> _PROGRAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTUD_NUMBERChanging(int value);
    partial void OnSTUD_NUMBERChanged();
    partial void OnSTUD_IDChanging(string value);
    partial void OnSTUD_IDChanged();
    partial void OnSTUD_PHOTOChanging(System.Data.Linq.Binary value);
    partial void OnSTUD_PHOTOChanged();
    partial void OnSTUD_FIRSTNAMEChanging(string value);
    partial void OnSTUD_FIRSTNAMEChanged();
    partial void OnSTUD_MIDDLENAMEChanging(string value);
    partial void OnSTUD_MIDDLENAMEChanged();
    partial void OnSTUD_LASTNAMEChanging(string value);
    partial void OnSTUD_LASTNAMEChanged();
    partial void OnSTUD_AGEChanging(string value);
    partial void OnSTUD_AGEChanged();
    partial void OnSTUD_BIRTH_DATEChanging(System.DateTime value);
    partial void OnSTUD_BIRTH_DATEChanged();
    partial void OnSTUD_PLACE_OF_BIRTHChanging(string value);
    partial void OnSTUD_PLACE_OF_BIRTHChanged();
    partial void OnSTUD_ADDRESSChanging(string value);
    partial void OnSTUD_ADDRESSChanged();
    partial void OnSTUD_EMAILChanging(string value);
    partial void OnSTUD_EMAILChanged();
    partial void OnSTUD_MOBILEChanging(string value);
    partial void OnSTUD_MOBILEChanged();
    partial void OnSTUD_GENDERChanging(string value);
    partial void OnSTUD_GENDERChanged();
    partial void OnSTUD_STATUSChanging(string value);
    partial void OnSTUD_STATUSChanged();
    partial void OnSTUD_CREATED_ATChanging(System.DateTime value);
    partial void OnSTUD_CREATED_ATChanged();
    partial void OnSTUD_UPDATED_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnSTUD_UPDATED_ATChanged();
    partial void OnCOLL_IDChanging(System.Nullable<int> value);
    partial void OnCOLL_IDChanged();
    partial void OnPROG_IDChanging(System.Nullable<int> value);
    partial void OnPROG_IDChanged();
    partial void OnYEAR_IDChanging(System.Nullable<int> value);
    partial void OnYEAR_IDChanged();
    #endregion
		
		public STUDENT()
		{
			this._COLLEGE = default(EntityRef<COLLEGE>);
			this._YEAR_LEVEL = default(EntityRef<YEAR_LEVEL>);
			this._PROGRAM = default(EntityRef<PROGRAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_NUMBER", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STUD_NUMBER
		{
			get
			{
				return this._STUD_NUMBER;
			}
			set
			{
				if ((this._STUD_NUMBER != value))
				{
					this.OnSTUD_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._STUD_NUMBER = value;
					this.SendPropertyChanged("STUD_NUMBER");
					this.OnSTUD_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_ID", AutoSync=AutoSync.Always, DbType="NVarChar(5)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string STUD_ID
		{
			get
			{
				return this._STUD_ID;
			}
			set
			{
				if ((this._STUD_ID != value))
				{
					this.OnSTUD_IDChanging(value);
					this.SendPropertyChanging();
					this._STUD_ID = value;
					this.SendPropertyChanged("STUD_ID");
					this.OnSTUD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_PHOTO", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary STUD_PHOTO
		{
			get
			{
				return this._STUD_PHOTO;
			}
			set
			{
				if ((this._STUD_PHOTO != value))
				{
					this.OnSTUD_PHOTOChanging(value);
					this.SendPropertyChanging();
					this._STUD_PHOTO = value;
					this.SendPropertyChanged("STUD_PHOTO");
					this.OnSTUD_PHOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_FIRSTNAME", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string STUD_FIRSTNAME
		{
			get
			{
				return this._STUD_FIRSTNAME;
			}
			set
			{
				if ((this._STUD_FIRSTNAME != value))
				{
					this.OnSTUD_FIRSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._STUD_FIRSTNAME = value;
					this.SendPropertyChanged("STUD_FIRSTNAME");
					this.OnSTUD_FIRSTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_MIDDLENAME", DbType="NVarChar(55)")]
		public string STUD_MIDDLENAME
		{
			get
			{
				return this._STUD_MIDDLENAME;
			}
			set
			{
				if ((this._STUD_MIDDLENAME != value))
				{
					this.OnSTUD_MIDDLENAMEChanging(value);
					this.SendPropertyChanging();
					this._STUD_MIDDLENAME = value;
					this.SendPropertyChanged("STUD_MIDDLENAME");
					this.OnSTUD_MIDDLENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_LASTNAME", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string STUD_LASTNAME
		{
			get
			{
				return this._STUD_LASTNAME;
			}
			set
			{
				if ((this._STUD_LASTNAME != value))
				{
					this.OnSTUD_LASTNAMEChanging(value);
					this.SendPropertyChanging();
					this._STUD_LASTNAME = value;
					this.SendPropertyChanged("STUD_LASTNAME");
					this.OnSTUD_LASTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_AGE", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string STUD_AGE
		{
			get
			{
				return this._STUD_AGE;
			}
			set
			{
				if ((this._STUD_AGE != value))
				{
					this.OnSTUD_AGEChanging(value);
					this.SendPropertyChanging();
					this._STUD_AGE = value;
					this.SendPropertyChanged("STUD_AGE");
					this.OnSTUD_AGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_BIRTH_DATE", DbType="Date NOT NULL")]
		public System.DateTime STUD_BIRTH_DATE
		{
			get
			{
				return this._STUD_BIRTH_DATE;
			}
			set
			{
				if ((this._STUD_BIRTH_DATE != value))
				{
					this.OnSTUD_BIRTH_DATEChanging(value);
					this.SendPropertyChanging();
					this._STUD_BIRTH_DATE = value;
					this.SendPropertyChanged("STUD_BIRTH_DATE");
					this.OnSTUD_BIRTH_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_PLACE_OF_BIRTH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string STUD_PLACE_OF_BIRTH
		{
			get
			{
				return this._STUD_PLACE_OF_BIRTH;
			}
			set
			{
				if ((this._STUD_PLACE_OF_BIRTH != value))
				{
					this.OnSTUD_PLACE_OF_BIRTHChanging(value);
					this.SendPropertyChanging();
					this._STUD_PLACE_OF_BIRTH = value;
					this.SendPropertyChanged("STUD_PLACE_OF_BIRTH");
					this.OnSTUD_PLACE_OF_BIRTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_ADDRESS", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string STUD_ADDRESS
		{
			get
			{
				return this._STUD_ADDRESS;
			}
			set
			{
				if ((this._STUD_ADDRESS != value))
				{
					this.OnSTUD_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._STUD_ADDRESS = value;
					this.SendPropertyChanged("STUD_ADDRESS");
					this.OnSTUD_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_EMAIL", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string STUD_EMAIL
		{
			get
			{
				return this._STUD_EMAIL;
			}
			set
			{
				if ((this._STUD_EMAIL != value))
				{
					this.OnSTUD_EMAILChanging(value);
					this.SendPropertyChanging();
					this._STUD_EMAIL = value;
					this.SendPropertyChanged("STUD_EMAIL");
					this.OnSTUD_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_MOBILE", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string STUD_MOBILE
		{
			get
			{
				return this._STUD_MOBILE;
			}
			set
			{
				if ((this._STUD_MOBILE != value))
				{
					this.OnSTUD_MOBILEChanging(value);
					this.SendPropertyChanging();
					this._STUD_MOBILE = value;
					this.SendPropertyChanged("STUD_MOBILE");
					this.OnSTUD_MOBILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_GENDER", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string STUD_GENDER
		{
			get
			{
				return this._STUD_GENDER;
			}
			set
			{
				if ((this._STUD_GENDER != value))
				{
					this.OnSTUD_GENDERChanging(value);
					this.SendPropertyChanging();
					this._STUD_GENDER = value;
					this.SendPropertyChanged("STUD_GENDER");
					this.OnSTUD_GENDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_STATUS", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string STUD_STATUS
		{
			get
			{
				return this._STUD_STATUS;
			}
			set
			{
				if ((this._STUD_STATUS != value))
				{
					this.OnSTUD_STATUSChanging(value);
					this.SendPropertyChanging();
					this._STUD_STATUS = value;
					this.SendPropertyChanged("STUD_STATUS");
					this.OnSTUD_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_CREATED_AT", DbType="Date NOT NULL")]
		public System.DateTime STUD_CREATED_AT
		{
			get
			{
				return this._STUD_CREATED_AT;
			}
			set
			{
				if ((this._STUD_CREATED_AT != value))
				{
					this.OnSTUD_CREATED_ATChanging(value);
					this.SendPropertyChanging();
					this._STUD_CREATED_AT = value;
					this.SendPropertyChanged("STUD_CREATED_AT");
					this.OnSTUD_CREATED_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_UPDATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> STUD_UPDATED_AT
		{
			get
			{
				return this._STUD_UPDATED_AT;
			}
			set
			{
				if ((this._STUD_UPDATED_AT != value))
				{
					this.OnSTUD_UPDATED_ATChanging(value);
					this.SendPropertyChanging();
					this._STUD_UPDATED_AT = value;
					this.SendPropertyChanged("STUD_UPDATED_AT");
					this.OnSTUD_UPDATED_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_ID", DbType="Int")]
		public System.Nullable<int> COLL_ID
		{
			get
			{
				return this._COLL_ID;
			}
			set
			{
				if ((this._COLL_ID != value))
				{
					if (this._COLLEGE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCOLL_IDChanging(value);
					this.SendPropertyChanging();
					this._COLL_ID = value;
					this.SendPropertyChanged("COLL_ID");
					this.OnCOLL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_ID", DbType="Int")]
		public System.Nullable<int> PROG_ID
		{
			get
			{
				return this._PROG_ID;
			}
			set
			{
				if ((this._PROG_ID != value))
				{
					if (this._PROGRAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPROG_IDChanging(value);
					this.SendPropertyChanging();
					this._PROG_ID = value;
					this.SendPropertyChanged("PROG_ID");
					this.OnPROG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_ID", DbType="Int")]
		public System.Nullable<int> YEAR_ID
		{
			get
			{
				return this._YEAR_ID;
			}
			set
			{
				if ((this._YEAR_ID != value))
				{
					if (this._YEAR_LEVEL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnYEAR_IDChanging(value);
					this.SendPropertyChanging();
					this._YEAR_ID = value;
					this.SendPropertyChanged("YEAR_ID");
					this.OnYEAR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COLLEGE_STUDENT", Storage="_COLLEGE", ThisKey="COLL_ID", OtherKey="COLL_ID", IsForeignKey=true)]
		public COLLEGE COLLEGE
		{
			get
			{
				return this._COLLEGE.Entity;
			}
			set
			{
				COLLEGE previousValue = this._COLLEGE.Entity;
				if (((previousValue != value) 
							|| (this._COLLEGE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COLLEGE.Entity = null;
						previousValue.STUDENTs.Remove(this);
					}
					this._COLLEGE.Entity = value;
					if ((value != null))
					{
						value.STUDENTs.Add(this);
						this._COLL_ID = value.COLL_ID;
					}
					else
					{
						this._COLL_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("COLLEGE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="YEAR_LEVEL_STUDENT", Storage="_YEAR_LEVEL", ThisKey="YEAR_ID", OtherKey="YEAR_ID", IsForeignKey=true)]
		public YEAR_LEVEL YEAR_LEVEL
		{
			get
			{
				return this._YEAR_LEVEL.Entity;
			}
			set
			{
				YEAR_LEVEL previousValue = this._YEAR_LEVEL.Entity;
				if (((previousValue != value) 
							|| (this._YEAR_LEVEL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._YEAR_LEVEL.Entity = null;
						previousValue.STUDENTs.Remove(this);
					}
					this._YEAR_LEVEL.Entity = value;
					if ((value != null))
					{
						value.STUDENTs.Add(this);
						this._YEAR_ID = value.YEAR_ID;
					}
					else
					{
						this._YEAR_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("YEAR_LEVEL");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROGRAM_STUDENT", Storage="_PROGRAM", ThisKey="PROG_ID", OtherKey="PROG_ID", IsForeignKey=true)]
		public PROGRAM PROGRAM
		{
			get
			{
				return this._PROGRAM.Entity;
			}
			set
			{
				PROGRAM previousValue = this._PROGRAM.Entity;
				if (((previousValue != value) 
							|| (this._PROGRAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PROGRAM.Entity = null;
						previousValue.STUDENTs.Remove(this);
					}
					this._PROGRAM.Entity = value;
					if ((value != null))
					{
						value.STUDENTs.Add(this);
						this._PROG_ID = value.PROG_ID;
					}
					else
					{
						this._PROG_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("PROGRAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YEAR_LEVEL")]
	public partial class YEAR_LEVEL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _YEAR_ID;
		
		private string _YEAR_NAME;
		
		private EntitySet<STUDENT> _STUDENTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYEAR_IDChanging(int value);
    partial void OnYEAR_IDChanged();
    partial void OnYEAR_NAMEChanging(string value);
    partial void OnYEAR_NAMEChanged();
    #endregion
		
		public YEAR_LEVEL()
		{
			this._STUDENTs = new EntitySet<STUDENT>(new Action<STUDENT>(this.attach_STUDENTs), new Action<STUDENT>(this.detach_STUDENTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int YEAR_ID
		{
			get
			{
				return this._YEAR_ID;
			}
			set
			{
				if ((this._YEAR_ID != value))
				{
					this.OnYEAR_IDChanging(value);
					this.SendPropertyChanging();
					this._YEAR_ID = value;
					this.SendPropertyChanged("YEAR_ID");
					this.OnYEAR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_NAME", DbType="NVarChar(55)")]
		public string YEAR_NAME
		{
			get
			{
				return this._YEAR_NAME;
			}
			set
			{
				if ((this._YEAR_NAME != value))
				{
					this.OnYEAR_NAMEChanging(value);
					this.SendPropertyChanging();
					this._YEAR_NAME = value;
					this.SendPropertyChanged("YEAR_NAME");
					this.OnYEAR_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="YEAR_LEVEL_STUDENT", Storage="_STUDENTs", ThisKey="YEAR_ID", OtherKey="YEAR_ID")]
		public EntitySet<STUDENT> STUDENTs
		{
			get
			{
				return this._STUDENTs;
			}
			set
			{
				this._STUDENTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_STUDENTs(STUDENT entity)
		{
			this.SendPropertyChanging();
			entity.YEAR_LEVEL = this;
		}
		
		private void detach_STUDENTs(STUDENT entity)
		{
			this.SendPropertyChanging();
			entity.YEAR_LEVEL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ID_STORAGE")]
	public partial class ID_STORAGE
	{
		
		private string _ID;
		
		public ID_STORAGE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(20)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROGRAM")]
	public partial class PROGRAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PROG_ID;
		
		private string _PROG_NAME;
		
		private System.Nullable<System.DateTime> _PROG_CREATED_AT;
		
		private System.Nullable<System.DateTime> _PROG_UPDATED_AT;
		
		private System.Nullable<int> _COLL_ID;
		
		private EntitySet<STUDENT> _STUDENTs;
		
		private EntityRef<COLLEGE> _COLLEGE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPROG_IDChanging(int value);
    partial void OnPROG_IDChanged();
    partial void OnPROG_NAMEChanging(string value);
    partial void OnPROG_NAMEChanged();
    partial void OnPROG_CREATED_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnPROG_CREATED_ATChanged();
    partial void OnPROG_UPDATED_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnPROG_UPDATED_ATChanged();
    partial void OnCOLL_IDChanging(System.Nullable<int> value);
    partial void OnCOLL_IDChanged();
    #endregion
		
		public PROGRAM()
		{
			this._STUDENTs = new EntitySet<STUDENT>(new Action<STUDENT>(this.attach_STUDENTs), new Action<STUDENT>(this.detach_STUDENTs));
			this._COLLEGE = default(EntityRef<COLLEGE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PROG_ID
		{
			get
			{
				return this._PROG_ID;
			}
			set
			{
				if ((this._PROG_ID != value))
				{
					this.OnPROG_IDChanging(value);
					this.SendPropertyChanging();
					this._PROG_ID = value;
					this.SendPropertyChanged("PROG_ID");
					this.OnPROG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_NAME", DbType="NVarChar(255)")]
		public string PROG_NAME
		{
			get
			{
				return this._PROG_NAME;
			}
			set
			{
				if ((this._PROG_NAME != value))
				{
					this.OnPROG_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PROG_NAME = value;
					this.SendPropertyChanged("PROG_NAME");
					this.OnPROG_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_CREATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> PROG_CREATED_AT
		{
			get
			{
				return this._PROG_CREATED_AT;
			}
			set
			{
				if ((this._PROG_CREATED_AT != value))
				{
					this.OnPROG_CREATED_ATChanging(value);
					this.SendPropertyChanging();
					this._PROG_CREATED_AT = value;
					this.SendPropertyChanged("PROG_CREATED_AT");
					this.OnPROG_CREATED_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_UPDATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> PROG_UPDATED_AT
		{
			get
			{
				return this._PROG_UPDATED_AT;
			}
			set
			{
				if ((this._PROG_UPDATED_AT != value))
				{
					this.OnPROG_UPDATED_ATChanging(value);
					this.SendPropertyChanging();
					this._PROG_UPDATED_AT = value;
					this.SendPropertyChanged("PROG_UPDATED_AT");
					this.OnPROG_UPDATED_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_ID", DbType="Int")]
		public System.Nullable<int> COLL_ID
		{
			get
			{
				return this._COLL_ID;
			}
			set
			{
				if ((this._COLL_ID != value))
				{
					if (this._COLLEGE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCOLL_IDChanging(value);
					this.SendPropertyChanging();
					this._COLL_ID = value;
					this.SendPropertyChanged("COLL_ID");
					this.OnCOLL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROGRAM_STUDENT", Storage="_STUDENTs", ThisKey="PROG_ID", OtherKey="PROG_ID")]
		public EntitySet<STUDENT> STUDENTs
		{
			get
			{
				return this._STUDENTs;
			}
			set
			{
				this._STUDENTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COLLEGE_PROGRAM", Storage="_COLLEGE", ThisKey="COLL_ID", OtherKey="COLL_ID", IsForeignKey=true)]
		public COLLEGE COLLEGE
		{
			get
			{
				return this._COLLEGE.Entity;
			}
			set
			{
				COLLEGE previousValue = this._COLLEGE.Entity;
				if (((previousValue != value) 
							|| (this._COLLEGE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COLLEGE.Entity = null;
						previousValue.PROGRAMs.Remove(this);
					}
					this._COLLEGE.Entity = value;
					if ((value != null))
					{
						value.PROGRAMs.Add(this);
						this._COLL_ID = value.COLL_ID;
					}
					else
					{
						this._COLL_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("COLLEGE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_STUDENTs(STUDENT entity)
		{
			this.SendPropertyChanging();
			entity.PROGRAM = this;
		}
		
		private void detach_STUDENTs(STUDENT entity)
		{
			this.SendPropertyChanging();
			entity.PROGRAM = null;
		}
	}
	
	public partial class SP_YEAR_LEVELResult
	{
		
		private string _YEAR_NAME;
		
		public SP_YEAR_LEVELResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_NAME", DbType="NVarChar(55)")]
		public string YEAR_NAME
		{
			get
			{
				return this._YEAR_NAME;
			}
			set
			{
				if ((this._YEAR_NAME != value))
				{
					this._YEAR_NAME = value;
				}
			}
		}
	}
	
	public partial class SP_PROGRAM_IDResult
	{
		
		private int _PROG_ID;
		
		public SP_PROGRAM_IDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_ID", DbType="Int NOT NULL")]
		public int PROG_ID
		{
			get
			{
				return this._PROG_ID;
			}
			set
			{
				if ((this._PROG_ID != value))
				{
					this._PROG_ID = value;
				}
			}
		}
	}
	
	public partial class SP_PROGRAMResult
	{
		
		private int _PROG_ID;
		
		private string _PROG_NAME;
		
		private System.Nullable<System.DateTime> _PROG_CREATED_AT;
		
		private System.Nullable<System.DateTime> _PROG_UPDATED_AT;
		
		public SP_PROGRAMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_ID", DbType="Int NOT NULL")]
		public int PROG_ID
		{
			get
			{
				return this._PROG_ID;
			}
			set
			{
				if ((this._PROG_ID != value))
				{
					this._PROG_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_NAME", DbType="NVarChar(255)")]
		public string PROG_NAME
		{
			get
			{
				return this._PROG_NAME;
			}
			set
			{
				if ((this._PROG_NAME != value))
				{
					this._PROG_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_CREATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> PROG_CREATED_AT
		{
			get
			{
				return this._PROG_CREATED_AT;
			}
			set
			{
				if ((this._PROG_CREATED_AT != value))
				{
					this._PROG_CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_UPDATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> PROG_UPDATED_AT
		{
			get
			{
				return this._PROG_UPDATED_AT;
			}
			set
			{
				if ((this._PROG_UPDATED_AT != value))
				{
					this._PROG_UPDATED_AT = value;
				}
			}
		}
	}
	
	public partial class SP_COLLEGEResult
	{
		
		private int _COLL_ID;
		
		private string _COLL_NAME;
		
		private System.Nullable<System.DateTime> _COLL_CREATED_AT;
		
		private System.Nullable<System.DateTime> _COLL_UPDATED_AT;
		
		public SP_COLLEGEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_ID", DbType="Int NOT NULL")]
		public int COLL_ID
		{
			get
			{
				return this._COLL_ID;
			}
			set
			{
				if ((this._COLL_ID != value))
				{
					this._COLL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_NAME", DbType="NVarChar(500)")]
		public string COLL_NAME
		{
			get
			{
				return this._COLL_NAME;
			}
			set
			{
				if ((this._COLL_NAME != value))
				{
					this._COLL_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_CREATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> COLL_CREATED_AT
		{
			get
			{
				return this._COLL_CREATED_AT;
			}
			set
			{
				if ((this._COLL_CREATED_AT != value))
				{
					this._COLL_CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_UPDATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> COLL_UPDATED_AT
		{
			get
			{
				return this._COLL_UPDATED_AT;
			}
			set
			{
				if ((this._COLL_UPDATED_AT != value))
				{
					this._COLL_UPDATED_AT = value;
				}
			}
		}
	}
	
	public partial class SP_COLLEGE_IDResult
	{
		
		private int _COLL_ID;
		
		public SP_COLLEGE_IDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_ID", DbType="Int NOT NULL")]
		public int COLL_ID
		{
			get
			{
				return this._COLL_ID;
			}
			set
			{
				if ((this._COLL_ID != value))
				{
					this._COLL_ID = value;
				}
			}
		}
	}
	
	public partial class SP_YEAR_LEVEL_IDResult
	{
		
		private int _YEAR_ID;
		
		public SP_YEAR_LEVEL_IDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_ID", DbType="Int NOT NULL")]
		public int YEAR_ID
		{
			get
			{
				return this._YEAR_ID;
			}
			set
			{
				if ((this._YEAR_ID != value))
				{
					this._YEAR_ID = value;
				}
			}
		}
	}
	
	public partial class SP_DISPLAY_STUDENT_RECORDSResult
	{
		
		private string _Id;
		
		private string _Name;
		
		private string _Age;
		
		private string _Status;
		
		private int _Year_level;
		
		private string _Program;
		
		private string _College;
		
		public SP_DISPLAY_STUDENT_RECORDSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(5)")]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(167) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Year level]", Storage="_Year_level", DbType="Int NOT NULL")]
		public int Year_level
		{
			get
			{
				return this._Year_level;
			}
			set
			{
				if ((this._Year_level != value))
				{
					this._Year_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Program", DbType="NVarChar(255)")]
		public string Program
		{
			get
			{
				return this._Program;
			}
			set
			{
				if ((this._Program != value))
				{
					this._Program = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_College", DbType="NVarChar(500)")]
		public string College
		{
			get
			{
				return this._College;
			}
			set
			{
				if ((this._College != value))
				{
					this._College = value;
				}
			}
		}
	}
	
	public partial class SP_SEARCH_STUDENT_RECORDS_BY_TEXTBOXResult
	{
		
		private string _Id;
		
		private string _Name;
		
		private string _Age;
		
		private string _Status;
		
		private int _Year_level;
		
		private string _Program;
		
		private string _College;
		
		public SP_SEARCH_STUDENT_RECORDS_BY_TEXTBOXResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(5)")]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(167) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Year level]", Storage="_Year_level", DbType="Int NOT NULL")]
		public int Year_level
		{
			get
			{
				return this._Year_level;
			}
			set
			{
				if ((this._Year_level != value))
				{
					this._Year_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Program", DbType="NVarChar(255)")]
		public string Program
		{
			get
			{
				return this._Program;
			}
			set
			{
				if ((this._Program != value))
				{
					this._Program = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_College", DbType="NVarChar(500)")]
		public string College
		{
			get
			{
				return this._College;
			}
			set
			{
				if ((this._College != value))
				{
					this._College = value;
				}
			}
		}
	}
	
	public partial class SP_DISPLAY_STUDENT_INFORMATIONResult
	{
		
		private int _STUD_NUMBER;
		
		private string _STUD_ID;
		
		private System.Data.Linq.Binary _STUD_PHOTO;
		
		private string _STUD_FIRSTNAME;
		
		private string _STUD_MIDDLENAME;
		
		private string _STUD_LASTNAME;
		
		private string _STUD_AGE;
		
		private System.DateTime _STUD_BIRTH_DATE;
		
		private string _STUD_PLACE_OF_BIRTH;
		
		private string _STUD_ADDRESS;
		
		private string _STUD_EMAIL;
		
		private string _STUD_MOBILE;
		
		private string _STUD_GENDER;
		
		private string _STUD_STATUS;
		
		private System.DateTime _STUD_CREATED_AT;
		
		private System.Nullable<System.DateTime> _STUD_UPDATED_AT;
		
		private System.Nullable<int> _COLL_ID;
		
		private System.Nullable<int> _PROG_ID;
		
		private System.Nullable<int> _YEAR_ID;
		
		private int _YEAR_ID1;
		
		private string _YEAR_NAME;
		
		private int _PROG_ID1;
		
		private string _PROG_NAME;
		
		private System.Nullable<System.DateTime> _PROG_CREATED_AT;
		
		private System.Nullable<System.DateTime> _PROG_UPDATED_AT;
		
		private int _COLL_ID1;
		
		private string _COLL_NAME;
		
		private System.Nullable<System.DateTime> _COLL_CREATED_AT;
		
		private System.Nullable<System.DateTime> _COLL_UPDATED_AT;
		
		private string _Name;
		
		public SP_DISPLAY_STUDENT_INFORMATIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_NUMBER", DbType="Int NOT NULL")]
		public int STUD_NUMBER
		{
			get
			{
				return this._STUD_NUMBER;
			}
			set
			{
				if ((this._STUD_NUMBER != value))
				{
					this._STUD_NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_ID", DbType="NVarChar(5)")]
		public string STUD_ID
		{
			get
			{
				return this._STUD_ID;
			}
			set
			{
				if ((this._STUD_ID != value))
				{
					this._STUD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_PHOTO", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary STUD_PHOTO
		{
			get
			{
				return this._STUD_PHOTO;
			}
			set
			{
				if ((this._STUD_PHOTO != value))
				{
					this._STUD_PHOTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_FIRSTNAME", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string STUD_FIRSTNAME
		{
			get
			{
				return this._STUD_FIRSTNAME;
			}
			set
			{
				if ((this._STUD_FIRSTNAME != value))
				{
					this._STUD_FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_MIDDLENAME", DbType="NVarChar(55)")]
		public string STUD_MIDDLENAME
		{
			get
			{
				return this._STUD_MIDDLENAME;
			}
			set
			{
				if ((this._STUD_MIDDLENAME != value))
				{
					this._STUD_MIDDLENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_LASTNAME", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string STUD_LASTNAME
		{
			get
			{
				return this._STUD_LASTNAME;
			}
			set
			{
				if ((this._STUD_LASTNAME != value))
				{
					this._STUD_LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_AGE", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string STUD_AGE
		{
			get
			{
				return this._STUD_AGE;
			}
			set
			{
				if ((this._STUD_AGE != value))
				{
					this._STUD_AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_BIRTH_DATE", DbType="Date NOT NULL")]
		public System.DateTime STUD_BIRTH_DATE
		{
			get
			{
				return this._STUD_BIRTH_DATE;
			}
			set
			{
				if ((this._STUD_BIRTH_DATE != value))
				{
					this._STUD_BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_PLACE_OF_BIRTH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string STUD_PLACE_OF_BIRTH
		{
			get
			{
				return this._STUD_PLACE_OF_BIRTH;
			}
			set
			{
				if ((this._STUD_PLACE_OF_BIRTH != value))
				{
					this._STUD_PLACE_OF_BIRTH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_ADDRESS", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string STUD_ADDRESS
		{
			get
			{
				return this._STUD_ADDRESS;
			}
			set
			{
				if ((this._STUD_ADDRESS != value))
				{
					this._STUD_ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_EMAIL", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string STUD_EMAIL
		{
			get
			{
				return this._STUD_EMAIL;
			}
			set
			{
				if ((this._STUD_EMAIL != value))
				{
					this._STUD_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_MOBILE", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string STUD_MOBILE
		{
			get
			{
				return this._STUD_MOBILE;
			}
			set
			{
				if ((this._STUD_MOBILE != value))
				{
					this._STUD_MOBILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_GENDER", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string STUD_GENDER
		{
			get
			{
				return this._STUD_GENDER;
			}
			set
			{
				if ((this._STUD_GENDER != value))
				{
					this._STUD_GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_STATUS", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string STUD_STATUS
		{
			get
			{
				return this._STUD_STATUS;
			}
			set
			{
				if ((this._STUD_STATUS != value))
				{
					this._STUD_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_CREATED_AT", DbType="Date NOT NULL")]
		public System.DateTime STUD_CREATED_AT
		{
			get
			{
				return this._STUD_CREATED_AT;
			}
			set
			{
				if ((this._STUD_CREATED_AT != value))
				{
					this._STUD_CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_UPDATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> STUD_UPDATED_AT
		{
			get
			{
				return this._STUD_UPDATED_AT;
			}
			set
			{
				if ((this._STUD_UPDATED_AT != value))
				{
					this._STUD_UPDATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_ID", DbType="Int")]
		public System.Nullable<int> COLL_ID
		{
			get
			{
				return this._COLL_ID;
			}
			set
			{
				if ((this._COLL_ID != value))
				{
					this._COLL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_ID", DbType="Int")]
		public System.Nullable<int> PROG_ID
		{
			get
			{
				return this._PROG_ID;
			}
			set
			{
				if ((this._PROG_ID != value))
				{
					this._PROG_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_ID", DbType="Int")]
		public System.Nullable<int> YEAR_ID
		{
			get
			{
				return this._YEAR_ID;
			}
			set
			{
				if ((this._YEAR_ID != value))
				{
					this._YEAR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_ID1", DbType="Int NOT NULL")]
		public int YEAR_ID1
		{
			get
			{
				return this._YEAR_ID1;
			}
			set
			{
				if ((this._YEAR_ID1 != value))
				{
					this._YEAR_ID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_NAME", DbType="NVarChar(55)")]
		public string YEAR_NAME
		{
			get
			{
				return this._YEAR_NAME;
			}
			set
			{
				if ((this._YEAR_NAME != value))
				{
					this._YEAR_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_ID1", DbType="Int NOT NULL")]
		public int PROG_ID1
		{
			get
			{
				return this._PROG_ID1;
			}
			set
			{
				if ((this._PROG_ID1 != value))
				{
					this._PROG_ID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_NAME", DbType="NVarChar(255)")]
		public string PROG_NAME
		{
			get
			{
				return this._PROG_NAME;
			}
			set
			{
				if ((this._PROG_NAME != value))
				{
					this._PROG_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_CREATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> PROG_CREATED_AT
		{
			get
			{
				return this._PROG_CREATED_AT;
			}
			set
			{
				if ((this._PROG_CREATED_AT != value))
				{
					this._PROG_CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_UPDATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> PROG_UPDATED_AT
		{
			get
			{
				return this._PROG_UPDATED_AT;
			}
			set
			{
				if ((this._PROG_UPDATED_AT != value))
				{
					this._PROG_UPDATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_ID1", DbType="Int NOT NULL")]
		public int COLL_ID1
		{
			get
			{
				return this._COLL_ID1;
			}
			set
			{
				if ((this._COLL_ID1 != value))
				{
					this._COLL_ID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_NAME", DbType="NVarChar(500)")]
		public string COLL_NAME
		{
			get
			{
				return this._COLL_NAME;
			}
			set
			{
				if ((this._COLL_NAME != value))
				{
					this._COLL_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_CREATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> COLL_CREATED_AT
		{
			get
			{
				return this._COLL_CREATED_AT;
			}
			set
			{
				if ((this._COLL_CREATED_AT != value))
				{
					this._COLL_CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_UPDATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> COLL_UPDATED_AT
		{
			get
			{
				return this._COLL_UPDATED_AT;
			}
			set
			{
				if ((this._COLL_UPDATED_AT != value))
				{
					this._COLL_UPDATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(167) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class SP_SPECIFIC_PROGRAM_FROM_COLLEGEResult
	{
		
		private int _PROG_ID;
		
		private string _PROG_NAME;
		
		private System.Nullable<System.DateTime> _PROG_CREATED_AT;
		
		private System.Nullable<System.DateTime> _PROG_UPDATED_AT;
		
		private System.Nullable<int> _COLL_ID;
		
		public SP_SPECIFIC_PROGRAM_FROM_COLLEGEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_ID", DbType="Int NOT NULL")]
		public int PROG_ID
		{
			get
			{
				return this._PROG_ID;
			}
			set
			{
				if ((this._PROG_ID != value))
				{
					this._PROG_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_NAME", DbType="NVarChar(255)")]
		public string PROG_NAME
		{
			get
			{
				return this._PROG_NAME;
			}
			set
			{
				if ((this._PROG_NAME != value))
				{
					this._PROG_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_CREATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> PROG_CREATED_AT
		{
			get
			{
				return this._PROG_CREATED_AT;
			}
			set
			{
				if ((this._PROG_CREATED_AT != value))
				{
					this._PROG_CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_UPDATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> PROG_UPDATED_AT
		{
			get
			{
				return this._PROG_UPDATED_AT;
			}
			set
			{
				if ((this._PROG_UPDATED_AT != value))
				{
					this._PROG_UPDATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLL_ID", DbType="Int")]
		public System.Nullable<int> COLL_ID
		{
			get
			{
				return this._COLL_ID;
			}
			set
			{
				if ((this._COLL_ID != value))
				{
					this._COLL_ID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
