#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment_System_DBMS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ENROLLMENT_DB")]
	public partial class EnrollmentDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSTUDENT(STUDENT instance);
    partial void UpdateSTUDENT(STUDENT instance);
    partial void DeleteSTUDENT(STUDENT instance);
    #endregion
		
		public EnrollmentDBDataContext() : 
				base(global::Enrollment_System_DBMS.Properties.Settings.Default.ENROLLMENT_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<STUDENT> STUDENTs
		{
			get
			{
				return this.GetTable<STUDENT>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERT")]
		public int SP_INSERT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_PHOTO", DbType="VarBinary(MAX)")] System.Data.Linq.Binary sTUD_PHOTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_FIRSTNAME", DbType="NVarChar(55)")] string sTUD_FIRSTNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_MIDDLENAME", DbType="NVarChar(55)")] string sTUD_MIDDLENAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_LASTNAME", DbType="NVarChar(55)")] string sTUD_LASTNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_AGE", DbType="NVarChar(2)")] string sTUD_AGE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_BIRTH_DATE", DbType="Date")] System.Nullable<System.DateTime> sTUD_BIRTH_DATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_PLACE_OF_BIRTH", DbType="NVarChar(100)")] string sTUD_PLACE_OF_BIRTH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_ADDRESS", DbType="NVarChar(100)")] string sTUD_ADDRESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_EMAIL", DbType="NVarChar(55)")] string sTUD_EMAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_MOBILE", DbType="NVarChar(13)")] string sTUD_MOBILE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_GENDER", DbType="NVarChar(55)")] string sTUD_GENDER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_CREATED_AT", DbType="Date")] System.Nullable<System.DateTime> sTUD_CREATED_AT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_UPDATED_AT", DbType="Date")] System.Nullable<System.DateTime> sTUD_UPDATED_AT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTUD_PHOTO, sTUD_FIRSTNAME, sTUD_MIDDLENAME, sTUD_LASTNAME, sTUD_AGE, sTUD_BIRTH_DATE, sTUD_PLACE_OF_BIRTH, sTUD_ADDRESS, sTUD_EMAIL, sTUD_MOBILE, sTUD_GENDER, sTUD_CREATED_AT, sTUD_UPDATED_AT);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STUDENT")]
	public partial class STUDENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STUD_NUMBER;
		
		private string _STUD_ID;
		
		private System.Data.Linq.Binary _STUD_PHOTO;
		
		private string _STUD_FIRSTNAME;
		
		private string _STUD_MIDDLENAME;
		
		private string _STUD_LASTNAME;
		
		private string _STUD_AGE;
		
		private System.DateTime _STUD_BIRTH_DATE;
		
		private string _STUD_PLACE_OF_BIRTH;
		
		private string _STUD_ADDRESS;
		
		private string _STUD_EMAIL;
		
		private string _STUD_MOBILE;
		
		private string _STUD_GENDER;
		
		private System.DateTime _STUD_CREATED_AT;
		
		private System.Nullable<System.DateTime> _STUD_UPDATED_AT;
		
		private System.Nullable<int> _ACAD_ID;
		
		private System.Nullable<int> _PROG_ID;
		
		private System.Nullable<int> _SUB_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTUD_NUMBERChanging(int value);
    partial void OnSTUD_NUMBERChanged();
    partial void OnSTUD_IDChanging(string value);
    partial void OnSTUD_IDChanged();
    partial void OnSTUD_PHOTOChanging(System.Data.Linq.Binary value);
    partial void OnSTUD_PHOTOChanged();
    partial void OnSTUD_FIRSTNAMEChanging(string value);
    partial void OnSTUD_FIRSTNAMEChanged();
    partial void OnSTUD_MIDDLENAMEChanging(string value);
    partial void OnSTUD_MIDDLENAMEChanged();
    partial void OnSTUD_LASTNAMEChanging(string value);
    partial void OnSTUD_LASTNAMEChanged();
    partial void OnSTUD_AGEChanging(string value);
    partial void OnSTUD_AGEChanged();
    partial void OnSTUD_BIRTH_DATEChanging(System.DateTime value);
    partial void OnSTUD_BIRTH_DATEChanged();
    partial void OnSTUD_PLACE_OF_BIRTHChanging(string value);
    partial void OnSTUD_PLACE_OF_BIRTHChanged();
    partial void OnSTUD_ADDRESSChanging(string value);
    partial void OnSTUD_ADDRESSChanged();
    partial void OnSTUD_EMAILChanging(string value);
    partial void OnSTUD_EMAILChanged();
    partial void OnSTUD_MOBILEChanging(string value);
    partial void OnSTUD_MOBILEChanged();
    partial void OnSTUD_GENDERChanging(string value);
    partial void OnSTUD_GENDERChanged();
    partial void OnSTUD_CREATED_ATChanging(System.DateTime value);
    partial void OnSTUD_CREATED_ATChanged();
    partial void OnSTUD_UPDATED_ATChanging(System.Nullable<System.DateTime> value);
    partial void OnSTUD_UPDATED_ATChanged();
    partial void OnACAD_IDChanging(System.Nullable<int> value);
    partial void OnACAD_IDChanged();
    partial void OnPROG_IDChanging(System.Nullable<int> value);
    partial void OnPROG_IDChanged();
    partial void OnSUB_IDChanging(System.Nullable<int> value);
    partial void OnSUB_IDChanged();
    #endregion
		
		public STUDENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_NUMBER", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STUD_NUMBER
		{
			get
			{
				return this._STUD_NUMBER;
			}
			set
			{
				if ((this._STUD_NUMBER != value))
				{
					this.OnSTUD_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._STUD_NUMBER = value;
					this.SendPropertyChanged("STUD_NUMBER");
					this.OnSTUD_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_ID", AutoSync=AutoSync.Always, DbType="NVarChar(5)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string STUD_ID
		{
			get
			{
				return this._STUD_ID;
			}
			set
			{
				if ((this._STUD_ID != value))
				{
					this.OnSTUD_IDChanging(value);
					this.SendPropertyChanging();
					this._STUD_ID = value;
					this.SendPropertyChanged("STUD_ID");
					this.OnSTUD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_PHOTO", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary STUD_PHOTO
		{
			get
			{
				return this._STUD_PHOTO;
			}
			set
			{
				if ((this._STUD_PHOTO != value))
				{
					this.OnSTUD_PHOTOChanging(value);
					this.SendPropertyChanging();
					this._STUD_PHOTO = value;
					this.SendPropertyChanged("STUD_PHOTO");
					this.OnSTUD_PHOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_FIRSTNAME", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string STUD_FIRSTNAME
		{
			get
			{
				return this._STUD_FIRSTNAME;
			}
			set
			{
				if ((this._STUD_FIRSTNAME != value))
				{
					this.OnSTUD_FIRSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._STUD_FIRSTNAME = value;
					this.SendPropertyChanged("STUD_FIRSTNAME");
					this.OnSTUD_FIRSTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_MIDDLENAME", DbType="NVarChar(55)")]
		public string STUD_MIDDLENAME
		{
			get
			{
				return this._STUD_MIDDLENAME;
			}
			set
			{
				if ((this._STUD_MIDDLENAME != value))
				{
					this.OnSTUD_MIDDLENAMEChanging(value);
					this.SendPropertyChanging();
					this._STUD_MIDDLENAME = value;
					this.SendPropertyChanged("STUD_MIDDLENAME");
					this.OnSTUD_MIDDLENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_LASTNAME", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string STUD_LASTNAME
		{
			get
			{
				return this._STUD_LASTNAME;
			}
			set
			{
				if ((this._STUD_LASTNAME != value))
				{
					this.OnSTUD_LASTNAMEChanging(value);
					this.SendPropertyChanging();
					this._STUD_LASTNAME = value;
					this.SendPropertyChanged("STUD_LASTNAME");
					this.OnSTUD_LASTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_AGE", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string STUD_AGE
		{
			get
			{
				return this._STUD_AGE;
			}
			set
			{
				if ((this._STUD_AGE != value))
				{
					this.OnSTUD_AGEChanging(value);
					this.SendPropertyChanging();
					this._STUD_AGE = value;
					this.SendPropertyChanged("STUD_AGE");
					this.OnSTUD_AGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_BIRTH_DATE", DbType="Date NOT NULL")]
		public System.DateTime STUD_BIRTH_DATE
		{
			get
			{
				return this._STUD_BIRTH_DATE;
			}
			set
			{
				if ((this._STUD_BIRTH_DATE != value))
				{
					this.OnSTUD_BIRTH_DATEChanging(value);
					this.SendPropertyChanging();
					this._STUD_BIRTH_DATE = value;
					this.SendPropertyChanged("STUD_BIRTH_DATE");
					this.OnSTUD_BIRTH_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_PLACE_OF_BIRTH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string STUD_PLACE_OF_BIRTH
		{
			get
			{
				return this._STUD_PLACE_OF_BIRTH;
			}
			set
			{
				if ((this._STUD_PLACE_OF_BIRTH != value))
				{
					this.OnSTUD_PLACE_OF_BIRTHChanging(value);
					this.SendPropertyChanging();
					this._STUD_PLACE_OF_BIRTH = value;
					this.SendPropertyChanged("STUD_PLACE_OF_BIRTH");
					this.OnSTUD_PLACE_OF_BIRTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_ADDRESS", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string STUD_ADDRESS
		{
			get
			{
				return this._STUD_ADDRESS;
			}
			set
			{
				if ((this._STUD_ADDRESS != value))
				{
					this.OnSTUD_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._STUD_ADDRESS = value;
					this.SendPropertyChanged("STUD_ADDRESS");
					this.OnSTUD_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_EMAIL", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string STUD_EMAIL
		{
			get
			{
				return this._STUD_EMAIL;
			}
			set
			{
				if ((this._STUD_EMAIL != value))
				{
					this.OnSTUD_EMAILChanging(value);
					this.SendPropertyChanging();
					this._STUD_EMAIL = value;
					this.SendPropertyChanged("STUD_EMAIL");
					this.OnSTUD_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_MOBILE", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string STUD_MOBILE
		{
			get
			{
				return this._STUD_MOBILE;
			}
			set
			{
				if ((this._STUD_MOBILE != value))
				{
					this.OnSTUD_MOBILEChanging(value);
					this.SendPropertyChanging();
					this._STUD_MOBILE = value;
					this.SendPropertyChanged("STUD_MOBILE");
					this.OnSTUD_MOBILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_GENDER", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string STUD_GENDER
		{
			get
			{
				return this._STUD_GENDER;
			}
			set
			{
				if ((this._STUD_GENDER != value))
				{
					this.OnSTUD_GENDERChanging(value);
					this.SendPropertyChanging();
					this._STUD_GENDER = value;
					this.SendPropertyChanged("STUD_GENDER");
					this.OnSTUD_GENDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_CREATED_AT", DbType="Date NOT NULL")]
		public System.DateTime STUD_CREATED_AT
		{
			get
			{
				return this._STUD_CREATED_AT;
			}
			set
			{
				if ((this._STUD_CREATED_AT != value))
				{
					this.OnSTUD_CREATED_ATChanging(value);
					this.SendPropertyChanging();
					this._STUD_CREATED_AT = value;
					this.SendPropertyChanged("STUD_CREATED_AT");
					this.OnSTUD_CREATED_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_UPDATED_AT", DbType="Date")]
		public System.Nullable<System.DateTime> STUD_UPDATED_AT
		{
			get
			{
				return this._STUD_UPDATED_AT;
			}
			set
			{
				if ((this._STUD_UPDATED_AT != value))
				{
					this.OnSTUD_UPDATED_ATChanging(value);
					this.SendPropertyChanging();
					this._STUD_UPDATED_AT = value;
					this.SendPropertyChanged("STUD_UPDATED_AT");
					this.OnSTUD_UPDATED_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACAD_ID", DbType="Int")]
		public System.Nullable<int> ACAD_ID
		{
			get
			{
				return this._ACAD_ID;
			}
			set
			{
				if ((this._ACAD_ID != value))
				{
					this.OnACAD_IDChanging(value);
					this.SendPropertyChanging();
					this._ACAD_ID = value;
					this.SendPropertyChanged("ACAD_ID");
					this.OnACAD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG_ID", DbType="Int")]
		public System.Nullable<int> PROG_ID
		{
			get
			{
				return this._PROG_ID;
			}
			set
			{
				if ((this._PROG_ID != value))
				{
					this.OnPROG_IDChanging(value);
					this.SendPropertyChanging();
					this._PROG_ID = value;
					this.SendPropertyChanged("PROG_ID");
					this.OnPROG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_ID", DbType="Int")]
		public System.Nullable<int> SUB_ID
		{
			get
			{
				return this._SUB_ID;
			}
			set
			{
				if ((this._SUB_ID != value))
				{
					this.OnSUB_IDChanging(value);
					this.SendPropertyChanging();
					this._SUB_ID = value;
					this.SendPropertyChanged("SUB_ID");
					this.OnSUB_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
